apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ns3-virtual-service
spec:
  hosts:
  - "<your dns name>"
  gateways:
  - ns3/asm-gateway
  http:
 # - match:
 #   - uri:
 #       prefix: /test
  - route: 
    - destination:
        host: store-v3
        port:
          number: 8080
